import {
  createCategory,
  createUnit,
  createProduct,
  deleteCategory,
  deleteUnit,
  deleteProduct,
  inventorySummary,
  inventorySummaryLessThan,
  listCategories,
  listCategoriesWithProducts,
  listProducts,
  listUnits,
  updateCategory,
  updateUnit,
  updateProduct,
} from "./handlers";

export const product = {
  listProducts,
  createProduct,
  deleteProduct,
  updateProduct,
  listCategories,
  inventorySummaryLessThan,
  inventorySummary,
  listCategoriesWithProducts,
  createCategory,
  updateCategory,
  deleteCategory,
  createUnit,
  deleteUnit,
  listUnits,
  updateUnit,
};
