import {
  listCustomers,
  listCustomersWithDebt,
  listCustomerType,
  listCustomerPayment,
  createCustomer,
  createCustomerType,
  createCustomerPayment,
  deleteCustomer,
  deleteCustomerType,
  deleteCustomerPayment,
  updateCustomer,
  updateCustomerType,
  updateCustomerPayment,
} from "./handlers";

export const customer = {
  listCustomers,
  listCustomersWithDebt,
  listCustomerType,
  listCustomerPayment,
  createCustomer,
  createCustomerType,
  createCustomerPayment,
  deleteCustomer,
  deleteCustomerType,
  deleteCustomerPayment,
  updateCustomer,
  updateCustomerType,
  updateCustomerPayment,
};
